# Generated by Django 4.2.14 on 2025-04-09 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0091_issue_customer_code_issue_hub_code_and_more'),
        ('db', '0092_alter_deprecateddashboardwidget_unique_together_and_more'),
    ]

    operations = [
    ]
