# Generated by Django 4.2.14 on 2025-04-11 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0092_issue_customer_name_issue_hub_name_issue_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.CharField(default='en', max_length=255),
        ),
    ]
