# Generated by Django migration for protected states feature

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0103_add_hub_code_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="state",
            name="is_protected",
            field=models.BooleanField(default=False),
        ),
    ]
