# Generated by Django 4.2.14 on 2026-05-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0107_protect_critical_states'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='start_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='target_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
